### ISSUE TITLE
you must  choose a bundler configuration

### ISSUE THREAD

**Issue by kindmaketheworldpeace** [actions-on-google/create-local-home-app#1]
i use npm init  @google/local/-home-app app/ --bundler webpack
but it say Missing require argument :bundler
i try other bundler like none rollup ,but it is not useful
node version v13.14.0
![image](https://user-images.githubusercontent.com/38469337/144532334-4a82fc38-4267-4f44-802c-a31c7ff9e423.png)

**Comment by robikuh** [comment]
The problem is occurring if npm is on latest version. Try with version 6.14.16

**Comment by huzhengxi** [comment]
> The problem is occurring if npm is on latest version. Try with version 6.14.16

me too.

**Comment by bgibb95** [comment]
Hi there. I have this issue too. Could we make a fix for this? @proppy @devunwired 

This repo is still used in [official Google documentation](https://developers.home.google.com/local-home/fulfillment-app#webpack-bundler) for a local fulfillment app

**Comment by vladyslavvolkov** [comment]
I've succeeded with npx on NodeJS v20 / npm v10:

```
npx @google/create-local-home-app house-of-chaos --bundler rollup
```
